import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { motion } from 'framer-motion'
import { ArrowRight, Bike, Clock3, MapPin, ShieldCheck, Sparkles } from 'lucide-react'
import { categoriesService, productsService } from '../../services/api'
import { restaurantConfig } from '../../config/restaurant'
import { useCartStore } from '../../stores/useCartStore'
import { useUiStore } from '../../stores/useUiStore'
import { Button, EmptyState, ErrorState, ProductCard, SearchInput, SectionHeading, Skeleton } from '../../components/ui'

export default function HomePage(){
  const [params]=useSearchParams(); const navigate=useNavigate(); const [category,setCategory]=useState('all'); const [search,setSearch]=useState(''); const [debounced,setDebounced]=useState('');
  const addItem=useCartStore((s)=>s.addItem),setOpen=useCartStore((s)=>s.setOpen),showToast=useUiStore((s)=>s.showToast)
  useEffect(()=>{ const timer=setTimeout(()=>setDebounced(search),300);return()=>clearTimeout(timer)},[search])
  useEffect(()=>{ if(params.get('search')) document.getElementById('pesquisa')?.focus() },[params])
  const categories=useQuery({queryKey:['categories'],queryFn:categoriesService.getCategories})
  const productQuery=useQuery({queryKey:['products',category,debounced],queryFn:()=>productsService.getProducts({category,search:debounced})})
  const popular=useMemo(()=>productQuery.data?.filter((product)=>product.featured).slice(0,4)||[],[productQuery.data])
  const add=(product)=>{ if(product.modifierGroups.length) return navigate(`/produto/${product.slug}`); addItem(product);showToast('Produto adicionado ao carrinho.');setOpen(false) }
  return <>
    <section className="page-shell pt-5 md:pt-8"><div className="relative grid min-h-[490px] overflow-hidden rounded-[2rem] bg-ink md:grid-cols-[1.05fr_.95fr]"><div className="relative z-10 flex flex-col justify-center p-7 text-white md:p-14"><motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}}><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-bold"><Sparkles size={14} className="text-amber-300"/> Feito hoje. Entregue quentinho.</span><h1 className="mt-5 max-w-xl font-display text-5xl font-bold leading-[1.02] tracking-tight md:text-7xl">Comida que sabe a <em className="font-normal text-brand-100">casa.</em></h1><p className="mt-5 max-w-md text-sm leading-6 text-stone-300 md:text-base">Sabores moçambicanos autênticos, ingredientes frescos e entrega própria em Maputo.</p><div className="mt-7 flex flex-wrap gap-3"><Button size="lg" onClick={()=>document.getElementById('cardapio')?.scrollIntoView()}>Ver cardápio <ArrowRight size={18}/></Button><Button size="lg" variant="ghost" className="text-white hover:bg-white/10" onClick={()=>document.getElementById('cardapio')?.scrollIntoView()}>Pedir agora</Button></div></motion.div></div><div className="relative min-h-72 overflow-hidden md:min-h-full"><img src="https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=82" alt="Prato moçambicano preparado com ingredientes frescos" className="absolute inset-0 size-full object-cover opacity-90"/><div className="absolute inset-0 bg-gradient-to-r from-ink via-transparent to-transparent"/><div className="absolute bottom-5 right-5 rounded-2xl bg-white/95 p-4 shadow-xl"><p className="text-xs font-bold text-stone-400">Entrega estimada</p><p className="mt-1 flex items-center gap-2 font-extrabold text-ink"><Clock3 size={18} className="text-brand-500"/>{restaurantConfig.deliveryTime}</p></div></div></div></section>
    <section className="page-shell -mt-4 relative z-10"><div className="grid gap-3 rounded-2xl bg-white p-4 shadow-soft sm:grid-cols-3"><div className="flex items-center gap-3 rounded-xl px-3 py-2"><span className="grid size-10 place-items-center rounded-full bg-brand-50 text-brand-600"><Bike size={20}/></span><div><p className="text-xs text-stone-400">Entrega própria</p><p className="text-sm font-bold">Rápida e cuidadosa</p></div></div><div className="flex items-center gap-3 rounded-xl px-3 py-2"><span className="grid size-10 place-items-center rounded-full bg-emerald-50 text-emerald-700"><ShieldCheck size={20}/></span><div><p className="text-xs text-stone-400">Compra segura</p><p className="text-sm font-bold">Pague como preferir</p></div></div><div className="flex items-center gap-3 rounded-xl px-3 py-2"><span className="grid size-10 place-items-center rounded-full bg-amber-50 text-amber-700"><MapPin size={20}/></span><div><p className="text-xs text-stone-400">Loja aberta</p><p className="text-sm font-bold">Hoje até às 22:00</p></div></div></div></section>
    <section className="page-shell py-16" id="cardapio"><SectionHeading eyebrow="Escolha o seu favorito" title="Nosso cardápio" description="Receitas preparadas na hora. Pesquise ou explore por categoria."/><div id="pesquisa" className="max-w-xl"><SearchInput value={search} onChange={(e)=>setSearch(e.target.value)}/></div><div className="no-scrollbar mt-5 flex gap-2 overflow-x-auto pb-2">{categories.data?.map((item)=><button key={item.id} onClick={()=>setCategory(item.id)} className={`whitespace-nowrap rounded-full px-4 py-2.5 text-sm font-bold transition ${category===item.id?'bg-ink text-white':'border border-stone-200 bg-white text-stone-600 hover:border-stone-300'}`}>{item.name}</button>)}</div>{productQuery.isPending?<div className="mt-8 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">{Array.from({length:8}).map((_,i)=><div key={i}><Skeleton className="aspect-[4/3]"/><Skeleton className="mt-3 h-5 w-2/3"/><Skeleton className="mt-2 h-4 w-full"/></div>)}</div>:productQuery.isError?<div className="mt-8"><ErrorState/></div>:!productQuery.data?.length?<div className="mt-8"><EmptyState title="Nenhum prato encontrado" description="Experimente outra palavra ou categoria."/></div>:<motion.div layout className="mt-8 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">{productQuery.data.map((product)=><ProductCard key={product.id} product={product} onAdd={add}/>)}</motion.div>}</section>
    {!search&&!category.includes('featured')&&popular.length>0&&<section className="bg-white py-16"><div className="page-shell"><SectionHeading eyebrow="Mais pedidos" title="Favoritos de Maputo"/><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{popular.map((product)=><ProductCard key={product.id} product={product} onAdd={add}/>)}</div></div></section>}
  </>
}
