import { Link, useLocation, useParams } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { Check, CheckCircle2, ChefHat, Clock3, MapPin, Navigation, Phone, Store, Truck } from 'lucide-react'
import { ordersService } from '../../services/api'
import { restaurantConfig } from '../../config/restaurant'
import { statusLabels } from '../../constants/app'
import { Button, Card, PriceDisplay, Skeleton, StatusBadge } from '../../components/ui'

const stages=[['RECEIVED','Recebido',Check],['CONFIRMED','Confirmado',CheckCircle2],['PREPARING','Em preparação',ChefHat],['READY_FOR_DELIVERY','Pronto',Store],['OUT_FOR_DELIVERY','Em entrega',Truck],['DELIVERED','Entregue',CheckCircle2]]
export function OrderConfirmedPage(){ const {state}=useLocation();const order=state?.order||{id:'1058',type:'DELIVERY',total:1250,status:'RECEIVED'};return <div className="page-shell py-12"><div className="mx-auto max-w-xl text-center"><span className="mx-auto grid size-20 place-items-center rounded-full bg-emerald-100 text-emerald-700"><CheckCircle2 size={40}/></span><p className="mt-6 text-xs font-extrabold uppercase tracking-[.18em] text-brand-600">Pedido #{order.id}</p><h1 className="mt-2 font-display text-4xl font-bold">Recebemos o seu pedido!</h1><p className="mt-3 text-stone-500">A cozinha já recebeu os detalhes. Avisaremos quando houver novidades.</p><Card className="mt-7 p-5 text-left"><div className="flex justify-between"><span className="text-sm text-stone-500">Total</span><PriceDisplay value={order.total} className="text-xl"/></div><div className="mt-3 flex justify-between"><span className="text-sm text-stone-500">Forma de receber</span><b className="text-sm">{order.type==='DELIVERY'?'Entrega':order.type==='PICKUP'?'Retirada':'Pré-pedido'}</b></div></Card><Link to={`/pedido/${order.id}`}><Button size="lg" className="mt-6 w-full">Acompanhar pedido</Button></Link><Link to="/" className="mt-4 block text-sm font-bold text-stone-500">Voltar ao cardápio</Link></div></div> }
export function OrderTrackingPage(){ const {id}=useParams();const {data:order,isPending}=useQuery({queryKey:['order',id],queryFn:()=>ordersService.getOrder(id),refetchInterval:15000});if(isPending)return <div className="page-shell py-10"><Skeleton className="mx-auto h-96 max-w-2xl"/></div>;const current=Math.max(0,stages.findIndex(([status])=>status===order.status));const courier=order.courierId?{name:'João Manuel',phone:'+258 84 765 1002'}:null;return <div className="page-shell py-8 md:py-12"><div className="mx-auto max-w-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-brand-600">Pedido #{order.id}</p><h1 className="mt-2 font-display text-4xl font-bold">{statusLabels[order.status]}</h1><p className="mt-2 flex items-center gap-2 text-sm text-stone-500"><Clock3 size={16}/>Actualizado agora</p></div><StatusBadge status={order.status} label={statusLabels[order.status]}/></div><Card className="mt-7 p-6"><div className="space-y-1">{stages.map(([status,label,Icon],index)=><div key={status} className="flex gap-4"><div className="flex flex-col items-center"><span className={`grid size-10 place-items-center rounded-full ${index<=current?'bg-brand-500 text-white':'bg-stone-100 text-stone-400'}`}><Icon size={18}/></span>{index<stages.length-1&&<span className={`h-10 w-0.5 ${index<current?'bg-brand-500':'bg-stone-200'}`}/>}</div><div className="pt-2"><p className={`text-sm font-bold ${index<=current?'text-ink':'text-stone-400'}`}>{label}</p>{index===current&&<p className="mt-1 text-xs text-stone-500">Estamos a tratar desta etapa.</p>}</div></div>)}</div></Card>{['OUT_FOR_DELIVERY','DELIVERED'].includes(order.status)&&<Card className="mt-5 p-6"><p className="text-xs font-bold uppercase tracking-wider text-stone-400">Código de confirmação</p><div className="mt-3 flex gap-2">{(order.code||'4821').split('').map((number,index)=><span key={index} className="grid size-13 place-items-center rounded-xl bg-ink text-xl font-black text-white">{number}</span>)}</div><p className="mt-3 text-sm text-stone-500">Informe somente quando receber seu pedido.</p></Card>}{courier&&<Card className="mt-5 flex items-center gap-4 p-5"><span className="grid size-12 place-items-center rounded-full bg-emerald-100 text-emerald-700"><Truck/></span><div className="flex-1"><p className="text-xs text-stone-400">Seu entregador</p><p className="font-bold">{courier.name}</p></div><a href={`tel:${courier.phone}`}><Button variant="secondary"><Phone size={17}/>Ligar</Button></a></Card>}<Card className="mt-5 p-5"><div className="flex gap-3"><MapPin className="text-brand-500"/><div><p className="font-bold">{order.type==='DELIVERY'?order.neighborhood:restaurantConfig.restaurantName}</p><p className="mt-1 text-sm text-stone-500">{order.reference||restaurantConfig.address}</p></div></div><Button variant="secondary" className="mt-4 w-full"><Navigation size={17}/>Abrir localização</Button></Card></div></div> }
