import { useMemo, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { ArrowLeft, Check, Clock3, ShoppingBag } from 'lucide-react'
import { productsService } from '../../services/api'
import { useCartStore } from '../../stores/useCartStore'
import { useUiStore } from '../../stores/useUiStore'
import { Button, ErrorState, PriceDisplay, QuantitySelector, Skeleton, Textarea } from '../../components/ui'

export default function ProductPage(){
  const {slug}=useParams();const navigate=useNavigate();const addItem=useCartStore((s)=>s.addItem);const showToast=useUiStore((s)=>s.showToast)
  const {data:product,isPending,isError}=useQuery({queryKey:['product',slug],queryFn:()=>productsService.getProductBySlug(slug)})
  const [selected,setSelected]=useState({});const [quantity,setQuantity]=useState(1);const [note,setNote]=useState('');const [error,setError]=useState('')
  const selections=useMemo(()=>Object.values(selected).flat(),[selected]);const total=product?(product.price+selections.reduce((s,o)=>s+(o.priceDelta||0),0))*quantity:0
  const toggle=(group,option)=>setSelected((current)=>{ if(group.type==='single') return {...current,[group.id]:[option]};const values=current[group.id]||[];return {...current,[group.id]:values.some((item)=>item.id===option.id)?values.filter((item)=>item.id!==option.id):values.length<group.maxSelections?[...values,option]:values} })
  const add=()=>{const missing=product.modifierGroups.find((group)=>group.required&&!(selected[group.id]?.length>=group.minSelections));if(missing){setError(`Seleccione uma opção em “${missing.name}”.`);return}addItem(product,{modifiers:selections,quantity,note});showToast('Produto adicionado ao carrinho.');navigate('/')}
  if(isPending)return <div className="page-shell grid gap-8 py-8 md:grid-cols-2"><Skeleton className="aspect-square"/><div><Skeleton className="h-10 w-2/3"/><Skeleton className="mt-4 h-24"/></div></div>
  if(isError)return <div className="page-shell py-10"><ErrorState/></div>
  if(!product)return <div className="page-shell py-20 text-center"><h1 className="font-display text-4xl font-bold">Produto não encontrado</h1><Button className="mt-6" onClick={()=>navigate('/')}>Voltar ao início</Button></div>
  return <div className="page-shell py-5 md:py-10"><Link to="/" className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-stone-500 hover:text-brand-600"><ArrowLeft size={17}/> Voltar ao cardápio</Link><div className="grid gap-8 lg:grid-cols-[1fr_.85fr]"><div className="sticky top-24 self-start overflow-hidden rounded-[2rem] bg-stone-200"><img src={product.image} alt={product.name} className="aspect-[4/3] size-full object-cover lg:aspect-square"/></div><div className="pb-24 lg:pb-0"><span className="text-xs font-extrabold uppercase tracking-[.18em] text-brand-600">Preparado na hora</span><h1 className="mt-3 font-display text-4xl font-bold tracking-tight md:text-5xl">{product.name}</h1><p className="mt-4 text-base leading-7 text-stone-500">{product.description}</p><div className="mt-5 flex items-center gap-5"><PriceDisplay value={product.price} className="text-2xl"/><span className="flex items-center gap-1.5 text-xs font-bold text-stone-500"><Clock3 size={15}/> 20–30 min</span></div><div className="mt-8 space-y-7">{product.modifierGroups.map((group)=><fieldset key={group.id}><legend className="mb-3 flex w-full items-center justify-between font-bold"><span>{group.name} {group.required&&<span className="text-brand-600">*</span>}</span><span className="text-xs font-medium text-stone-400">{group.type==='single'?'Escolha 1':`Até ${group.maxSelections}`}</span></legend><div className="space-y-2">{group.options.map((option)=>{const checked=selected[group.id]?.some((item)=>item.id===option.id);return <label key={option.id} className={`flex cursor-pointer items-center justify-between rounded-xl border p-4 transition ${checked?'border-brand-500 bg-brand-50':'border-stone-200 bg-white hover:border-stone-300'}`}><span className="flex items-center gap-3"><input type={group.type==='single'?'radio':'checkbox'} name={group.id} checked={checked||false} onChange={()=>toggle(group,option)} className="sr-only"/><span className={`grid size-5 place-items-center ${group.type==='single'?'rounded-full':'rounded-md'} border ${checked?'border-brand-500 bg-brand-500 text-white':'border-stone-300'}`}>{checked&&<Check size={13}/>}</span><span className="text-sm font-semibold">{option.name}</span></span>{option.priceDelta>0&&<span className="text-sm font-bold text-stone-500">+ {option.priceDelta} MT</span>}</label>})}</div></fieldset>)}</div><Textarea className="mt-7" label="Alguma observação?" placeholder="Ex.: sem picante, molho à parte..." value={note} onChange={(e)=>setNote(e.target.value)}/>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<div className="mt-7 flex items-center justify-between rounded-2xl bg-white p-4 shadow-sm"><QuantitySelector value={quantity} onChange={setQuantity}/><Button size="lg" onClick={add} disabled={!product.available}><ShoppingBag size={18}/>Adicionar · <PriceDisplay value={total}/></Button></div></div></div></div>
}
