import { useState } from 'react'
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { ArrowLeft, Eye, EyeOff, LockKeyhole, Phone, ShieldCheck } from 'lucide-react'
import { authService } from '../../services/api'
import { useAuthStore } from '../../stores/useAuthStore'
import { restaurantConfig } from '../../config/restaurant'
import { mozambiqueLocations } from '../../constants/app'
import { Button, Card, Input, Select } from '../../components/ui'

const phoneSchema=z.string().min(9,'Introduza um número válido.')
const loginSchema=z.object({phone:phoneSchema,password:z.string().min(4,'A senha deve ter pelo menos 4 caracteres.')})
function AuthShell({eyebrow,title,subtitle,children}){ return <main className="grid min-h-screen bg-cream lg:grid-cols-[.9fr_1.1fr]"><section className="flex items-center justify-center p-5 md:p-10"><div className="w-full max-w-md"><Link to="/" className="mb-10 inline-flex items-center gap-2 text-sm font-bold text-stone-500"><ArrowLeft size={17}/>Voltar à loja</Link><p className="text-xs font-extrabold uppercase tracking-[.18em] text-brand-600">{eyebrow}</p><h1 className="mt-3 font-display text-4xl font-bold tracking-tight md:text-5xl">{title}</h1><p className="mt-3 text-sm leading-6 text-stone-500">{subtitle}</p>{children}</div></section><aside className="relative hidden overflow-hidden bg-ink lg:block"><img src="https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1400&q=82" alt="Mesa preparada no restaurante" className="absolute inset-0 size-full object-cover opacity-60"/><div className="absolute inset-0 bg-gradient-to-t from-ink via-transparent"/><div className="absolute bottom-12 left-12 right-12 text-white"><p className="font-display text-4xl font-bold">{restaurantConfig.tagline}</p><p className="mt-3 max-w-md text-sm text-stone-300">Peça, acompanhe e receba. Tudo simples, do jeito que deve ser.</p></div></aside></main> }

export function LoginPage(){
  const user=useAuthStore((s)=>s.user),setUser=useAuthStore((s)=>s.setUser),returnTo=useAuthStore((s)=>s.returnTo),navigate=useNavigate(),location=useLocation();const [show,setShow]=useState(false),[serverError,setServerError]=useState('')
  const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm({resolver:zodResolver(loginSchema),defaultValues:{phone:'+258 84 000 000',password:'1234'}})
  if(user){const destination=user.role==='COURIER'?'/delivery':['OWNER','ADMIN'].includes(user.role)?'/admin':returnTo||'/';return <Navigate to={destination} replace/>}
  const submit=async(values)=>{try{const result=await authService.login(values);setUser(result);const from=location.state?.from||returnTo;navigate(result.role==='COURIER'?'/delivery':['OWNER','ADMIN'].includes(result.role)?'/admin':from||'/')}catch{setServerError('Não foi possível entrar. Verifique os dados.')}}
  return <AuthShell eyebrow="Bem-vindo" title="Entre na sua conta" subtitle="Um único acesso para clientes, equipa e entregadores."><form onSubmit={handleSubmit(submit)} className="mt-8 space-y-4"><Input label="Número de telefone" icon={Phone} error={errors.phone?.message} {...register('phone')}/><div className="relative"><Input label="Senha" icon={LockKeyhole} type={show?'text':'password'} error={errors.password?.message} {...register('password')}/><button type="button" aria-label="Mostrar senha" className="absolute right-4 top-10 text-stone-400" onClick={()=>setShow(!show)}>{show?<EyeOff size={19}/>:<Eye size={19}/>}</button></div>{serverError&&<p className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{serverError}</p>}<div className="flex justify-end"><Link to="/recuperar-senha" className="text-sm font-bold text-brand-600">Esqueceu a senha?</Link></div><Button size="lg" className="w-full" loading={isSubmitting}>Entrar</Button></form><p className="mt-7 text-center text-sm text-stone-500">Ainda não tem conta? <Link to="/cadastro" className="font-bold text-brand-600">Criar conta</Link></p><Card className="mt-7 bg-stone-50 p-4 text-xs leading-5 text-stone-500"><b className="text-ink">Acessos demo:</b> final 000 proprietário, 111 administrador, 222 entregador. Qualquer outro número entra como cliente. Senha: 1234.</Card></AuthShell>
}

const registerSchema=z.object({name:z.string().min(3,'Introduza seu nome.'),phone:phoneSchema,province:z.string().min(1,'Seleccione a província.'),city:z.string().min(1,'Seleccione a cidade.'),password:z.string().min(6,'Use pelo menos 6 caracteres.'),confirm:z.string()}).refine((v)=>v.password===v.confirm,{path:['confirm'],message:'As senhas não coincidem.'})
export function RegisterPage(){ const navigate=useNavigate();const [province,setProvince]=useState('Maputo');const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm({resolver:zodResolver(registerSchema),defaultValues:{province:'Maputo',city:'Maputo Cidade'}});const submit=async(values)=>{await authService.register(values);navigate('/verificar-telefone',{state:{phone:values.phone}})};return <AuthShell eyebrow="Conta de cliente" title="Crie a sua conta" subtitle="Leva menos de um minuto. Pediremos o endereço apenas no checkout."><form onSubmit={handleSubmit(submit)} className="mt-8 grid gap-4 sm:grid-cols-2"><Input className="sm:col-span-2" label="Nome completo" error={errors.name?.message} {...register('name')}/><Input className="sm:col-span-2" label="Número de telefone" placeholder="+258 84 000 0000" error={errors.phone?.message} {...register('phone')}/><Select label="Província" error={errors.province?.message} {...register('province')} onChange={(e)=>{register('province').onChange(e);setProvince(e.target.value)}}>{Object.keys(mozambiqueLocations).map((value)=><option key={value}>{value}</option>)}</Select><Select label="Distrito/Cidade" error={errors.city?.message} {...register('city')}>{mozambiqueLocations[province]?.map((value)=><option key={value}>{value}</option>)}</Select><Input label="Senha" type="password" error={errors.password?.message} {...register('password')}/><Input label="Confirmar senha" type="password" error={errors.confirm?.message} {...register('confirm')}/><Button size="lg" className="sm:col-span-2" loading={isSubmitting}>Criar conta</Button></form><p className="mt-6 text-center text-sm text-stone-500">Já tem conta? <Link className="font-bold text-brand-600" to="/login">Entrar</Link></p></AuthShell> }

export function VerifyPhonePage(){ const navigate=useNavigate(),location=useLocation();const [digits,setDigits]=useState(['','','','','','']),[error,setError]=useState(''),[loading,setLoading]=useState(false);const confirm=async()=>{setLoading(true);try{await authService.verifyOtp(digits.join(''));navigate('/login')}catch(e){setError(e.message)}finally{setLoading(false)}};return <AuthShell eyebrow="Verificação" title="Confirme o telefone" subtitle={`Enviamos um código para ${location.state?.phone||'+258 84 *** ****'}.`}><div className="mt-8 flex gap-2">{digits.map((digit,index)=><input key={index} value={digit} maxLength={1} aria-label={`Dígito ${index+1}`} onChange={(e)=>{const next=[...digits];next[index]=e.target.value.replace(/\D/g,'');setDigits(next);if(e.target.value)e.target.nextElementSibling?.focus()}} className="h-14 min-w-0 flex-1 rounded-xl border border-stone-200 bg-white text-center text-xl font-black outline-none focus:border-brand-500"/>)}</div>{error&&<p className="mt-4 text-sm font-bold text-red-600">{error}</p>}<Button size="lg" className="mt-6 w-full" loading={loading} onClick={confirm}>Confirmar</Button><p className="mt-5 text-center text-sm text-stone-500">Não recebeu? <button className="font-bold text-brand-600">Reenviar em 00:42</button></p><p className="mt-2 text-center text-xs text-stone-400">Modo demo: use 123456</p></AuthShell> }

export function RecoverPasswordPage(){ const [step,setStep]=useState(0);return <AuthShell eyebrow="Segurança" title="Recuperar senha" subtitle="Vamos confirmar a sua identidade pelo telefone."><div className="mt-8">{step===0&&<><Input label="Número de telefone" icon={Phone} placeholder="+258 84 000 0000"/><Button size="lg" className="mt-5 w-full" onClick={()=>setStep(1)}>Enviar código</Button></>}{step===1&&<><div className="rounded-2xl bg-emerald-50 p-4 text-sm text-emerald-800"><ShieldCheck className="mb-2"/>Código enviado. Introduza 123456.</div><Input className="mt-4" label="Código OTP"/><Button size="lg" className="mt-5 w-full" onClick={()=>setStep(2)}>Confirmar código</Button></>}{step===2&&<><Input label="Nova senha" type="password"/><Input className="mt-4" label="Confirmar senha" type="password"/><Link to="/login"><Button size="lg" className="mt-5 w-full">Guardar e entrar</Button></Link></>}</div></AuthShell> }
