import { NavLink, Outlet, useNavigate } from 'react-router-dom'
import { Bell, BookOpen, CalendarDays, ChevronDown, ClipboardList, LayoutDashboard, LogOut, Menu, Package, Settings, ShieldCheck, Truck, UserCog, Users, X } from 'lucide-react'
import { restaurantConfig } from '../../config/restaurant'
import { useAuthStore } from '../../stores/useAuthStore'
import { useUiStore } from '../../stores/useUiStore'
import { IconButton } from '../ui'

const links=[
  ['/admin','Dashboard',LayoutDashboard],['/admin/pedidos','Pedidos',ClipboardList],['/admin/reservas','Reservas',CalendarDays],
  ['/admin/cardapio/produtos','Produtos',Package],['/admin/cardapio/categorias','Categorias',BookOpen],['/admin/cardapio/complementos','Complementos',ChevronDown],
  ['/admin/entregadores','Entregadores',Truck],['/admin/clientes','Clientes',Users],['/admin/equipe','Equipe',UserCog],['/admin/auditoria','Auditoria',ShieldCheck],['/admin/configuracoes/restaurante','Configurações',Settings],
]
function Sidebar({close}){ const {logout}=useAuthStore();const navigate=useNavigate();return <div className="flex h-full flex-col bg-ink p-4 text-white"><div className="mb-7 flex items-center justify-between px-2 py-2"><span className="font-display text-xl font-bold">{restaurantConfig.restaurantName}<small className="ml-2 rounded bg-white/10 px-2 py-1 font-sans text-[10px] uppercase tracking-wider">Gestão</small></span>{close&&<button onClick={close}><X/></button>}</div><nav className="space-y-1">{links.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/admin'} onClick={close} className={({isActive})=>`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold transition ${isActive?'bg-brand-500 text-white':'text-stone-300 hover:bg-white/8 hover:text-white'}`}><Icon size={18}/>{label}</NavLink>)}</nav><button onClick={()=>{logout();navigate('/login')}} className="mt-auto flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-stone-400 hover:bg-white/8"><LogOut size={18}/>Sair</button></div> }
export function AdminLayout(){ const menu=useUiStore((s)=>s.adminMenu),setMenu=useUiStore((s)=>s.setAdminMenu);const user=useAuthStore((s)=>s.user);return <div className="min-h-screen overflow-x-hidden bg-[#f5f4f0]"><aside className="fixed inset-y-0 left-0 hidden w-64 lg:block"><Sidebar/></aside>{menu&&<div className="fixed inset-0 z-50 lg:hidden"><button className="absolute inset-0 bg-black/40" onClick={()=>setMenu(false)}/><aside className="relative h-full w-72"><Sidebar close={()=>setMenu(false)}/></aside></div>}<div className="min-w-0 lg:pl-64"><header className="sticky top-0 z-30 flex h-18 items-center justify-between border-b border-stone-200 bg-white/90 px-4 backdrop-blur md:px-8"><div className="flex items-center gap-3"><IconButton label="Menu" className="lg:hidden" onClick={()=>setMenu(true)}><Menu size={20}/></IconButton><div><p className="text-xs font-bold uppercase tracking-wider text-stone-400">Operação</p><p className="text-sm font-bold">Maputo · <span className="text-emerald-600">Loja aberta</span></p></div></div><div className="flex items-center gap-3"><IconButton label="Notificações"><Bell size={19}/></IconButton><div className="hidden text-right sm:block"><p className="text-sm font-bold">{user?.name||'Sofia Mabote'}</p><p className="text-xs text-stone-400">{user?.role||'OWNER'}</p></div><span className="grid size-10 place-items-center rounded-full bg-brand-100 font-bold text-brand-700">{(user?.name||'S')[0]}</span></div></header><main className="min-w-0 p-4 md:p-8"><Outlet/></main></div></div> }
