import { useEffect, useState } from 'react'
import { Link, NavLink, Outlet, useLocation, useNavigate } from 'react-router-dom'
import { Clock3, MapPin, Menu, Search, ShoppingBag, UserRound, WifiOff } from 'lucide-react'
import { restaurantConfig } from '../../config/restaurant'
import { useCartStore } from '../../stores/useCartStore'
import { useAuthStore } from '../../stores/useAuthStore'
import { useUiStore } from '../../stores/useUiStore'
import { Button, Drawer, EmptyState, IconButton, PriceDisplay, QuantitySelector } from '../ui'

function Brand(){ return <Link to="/" className="flex items-center gap-2.5"><span className="grid size-10 place-items-center rounded-xl bg-brand-500 font-display text-xl font-black text-white">S</span><span className="font-display text-xl font-bold tracking-tight">{restaurantConfig.restaurantName}</span></Link> }

function CartDrawer(){
  const {items,open,setOpen,removeItem,updateQuantity,subtotal}=useCartStore(); const navigate=useNavigate()
  return <Drawer open={open} onClose={()=>setOpen(false)} title="O seu carrinho" footer={items.length>0&&<><div className="mb-4 flex items-center justify-between"><span className="text-sm text-stone-500">Subtotal</span><PriceDisplay value={subtotal()} className="text-xl"/></div><Button className="w-full" size="lg" onClick={()=>{setOpen(false);navigate('/checkout')}}>Finalizar pedido</Button></>}>
    {!items.length?<EmptyState title="Carrinho vazio" description="Escolha algo delicioso do nosso cardápio." action={<Button variant="secondary" onClick={()=>setOpen(false)}>Ver cardápio</Button>}/>:<div className="space-y-4">{items.map((item)=><div key={`${item.key}-${item.note}`} className="flex gap-3 rounded-2xl bg-white p-3 shadow-sm"><img src={item.image} alt="" className="size-20 rounded-xl object-cover"/><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><h3 className="font-bold">{item.name}</h3><button className="text-xs font-bold text-red-600" onClick={()=>removeItem(item.key)}>Remover</button></div>{item.modifiers.length>0&&<p className="mt-1 line-clamp-2 text-xs text-stone-500">{item.modifiers.map((m)=>m.name).join(' · ')}</p>}<div className="mt-3 flex items-center justify-between"><QuantitySelector value={item.quantity} onChange={(value)=>updateQuantity(item.key,value)}/><PriceDisplay value={item.unitPrice*item.quantity}/></div></div></div>)}</div>}
  </Drawer>
}

export function StoreLayout(){
  const {items,setOpen,count,subtotal}=useCartStore(); const user=useAuthStore((s)=>s.user); const toast=useUiStore((s)=>s.toast); const [online,setOnline]=useState(navigator.onLine); const location=useLocation()
  useEffect(()=>{ const up=()=>setOnline(true),down=()=>setOnline(false); window.addEventListener('online',up);window.addEventListener('offline',down);return()=>{window.removeEventListener('online',up);window.removeEventListener('offline',down)} },[])
  return <div className="min-h-screen bg-cream pb-24 md:pb-0"><header className="glass sticky top-0 z-30 border-b border-stone-200/80"><div className="page-shell flex h-18 items-center justify-between"><Brand/><nav className="hidden items-center gap-7 text-sm font-bold md:flex"><NavLink to="/" className={({isActive})=>isActive?'text-brand-600':'text-stone-600 hover:text-ink'}>Início</NavLink><a href="/#cardapio" className="text-stone-600 hover:text-ink">Cardápio</a><Link to="/?search=1" aria-label="Pesquisar" className="text-stone-600"><Search size={20}/></Link><Link to={user?'/conta':'/login'} className="flex items-center gap-2 text-stone-600"><UserRound size={20}/>{user?.name?.split(' ')[0]||'Conta'}</Link><Button variant="dark" onClick={()=>setOpen(true)}><ShoppingBag size={18}/>{count()>0?`${count()} · ${subtotal()} MT`:'Carrinho'}</Button></nav><div className="flex items-center gap-2 md:hidden"><Link to="/?search=1"><IconButton label="Pesquisar"><Search size={19}/></IconButton></Link><Link to={user?'/conta':'/login'}><IconButton label="Conta"><Menu size={20}/></IconButton></Link></div></div></header>{!online&&<div className="flex items-center justify-center gap-2 bg-ink px-4 py-2 text-xs font-bold text-white"><WifiOff size={14}/> Sem ligação. Dados podem estar desactualizados.</div>}<main key={location.pathname}><Outlet/></main><footer className="mt-20 border-t border-stone-200 bg-white"><div className="page-shell grid gap-10 py-12 md:grid-cols-3"><div><Brand/><p className="mt-4 max-w-sm text-sm leading-6 text-stone-500">{restaurantConfig.description}</p></div><div><h3 className="font-bold">Visite-nos</h3><p className="mt-3 flex gap-2 text-sm text-stone-500"><MapPin size={17}/>{restaurantConfig.address}</p><p className="mt-3 flex gap-2 text-sm text-stone-500"><Clock3 size={17}/>Todos os dias, 08:00–22:00</p></div><div><h3 className="font-bold">Contacto</h3><a className="mt-3 block text-sm text-stone-500" href={`tel:${restaurantConfig.restaurantPhone}`}>{restaurantConfig.restaurantPhone}</a><a className="mt-2 block text-sm font-bold text-brand-600" href={`https://wa.me/${restaurantConfig.restaurantWhatsapp}`}>Falar no WhatsApp</a></div></div></footer>{items.length>0&&<button onClick={()=>setOpen(true)} className="fixed inset-x-3 bottom-3 z-30 flex h-15 items-center justify-between rounded-2xl bg-ink px-5 font-bold text-white shadow-2xl md:hidden"><span className="flex items-center gap-2"><ShoppingBag size={19}/>{count()} {count()===1?'item':'itens'}</span><span>{subtotal()} MT · Ver carrinho</span></button>}<CartDrawer/>{toast&&<div className="fixed left-1/2 top-20 z-[80] -translate-x-1/2 rounded-xl bg-ink px-5 py-3 text-sm font-bold text-white shadow-xl">{toast.message}</div>}</div>
}
