import { Link, useLocation, useParams } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { ChevronRight, Home, LockKeyhole, MapPin, Package, Pencil, Plus, RotateCcw, ShieldCheck, UserRound } from 'lucide-react'
import { ordersService } from '../../services/api'
import { useAuthStore } from '../../stores/useAuthStore'
import { Button, Card, Input, PriceDisplay, StatusBadge } from '../../components/ui'
import { statusLabels } from '../../constants/app'

const menu=[['/conta/perfil','Meus dados',UserRound],['/conta/pedidos','Meus pedidos',Package],['/conta/enderecos','Endereços',MapPin],['/conta/seguranca','Segurança',LockKeyhole]]
export function AccountHome(){ const user=useAuthStore((s)=>s.user);return <div className="page-shell py-8"><p className="text-xs font-extrabold uppercase tracking-wider text-brand-600">Minha conta</p><h1 className="mt-2 font-display text-4xl font-bold">Olá, {user?.name?.split(' ')[0]||'Amélia'}</h1><div className="mt-7 grid gap-4 md:grid-cols-2">{menu.map(([to,label,Icon])=><Link key={to} to={to}><Card className="flex items-center gap-4 p-5 transition hover:-translate-y-0.5 hover:shadow-soft"><span className="grid size-11 place-items-center rounded-xl bg-brand-50 text-brand-600"><Icon size={21}/></span><b className="flex-1">{label}</b><ChevronRight className="text-stone-300"/></Card></Link>)}</div></div> }
export function ProfilePage(){ const user=useAuthStore((s)=>s.user);return <AccountSection title="Meus dados" subtitle="Mantenha os seus dados actualizados."><Card className="grid gap-4 p-5 sm:grid-cols-2"><Input label="Nome" defaultValue={user?.name||'Amélia Cossa'}/><Input label="Telefone" defaultValue={user?.phone||'+258 84 456 7832'}/><Input label="Província" defaultValue="Maputo"/><Input label="Distrito/Cidade" defaultValue="Maputo Cidade"/><Button className="sm:col-span-2 sm:justify-self-start">Guardar alterações</Button></Card></AccountSection> }
export function CustomerOrdersPage(){ const {data=[]}=useQuery({queryKey:['orders'],queryFn:ordersService.getOrders});return <AccountSection title="Meus pedidos" subtitle="Acompanhe e repita os seus favoritos."><div className="space-y-3">{data.slice(0,4).map((order)=><Link key={order.id} to={`/conta/pedidos/${order.id}`}><Card className="mb-3 flex items-center gap-4 p-5"><span className="grid size-12 place-items-center rounded-xl bg-stone-100 font-bold">#{order.id}</span><div className="min-w-0 flex-1"><p className="font-bold">{order.type==='DELIVERY'?'Entrega':order.type==='PICKUP'?'Retirada':'Pré-pedido'}</p><p className="mt-1 text-xs text-stone-500">15 Ago 2026 · {order.items} itens</p></div><div className="text-right"><PriceDisplay value={order.total}/><div className="mt-2"><StatusBadge status={order.status} label={statusLabels[order.status]}/></div></div></Card></Link>)}</div></AccountSection> }
export function CustomerOrderDetail(){ const {id}=useParams();const {data:order}=useQuery({queryKey:['order',id],queryFn:()=>ordersService.getOrder(id)});if(!order)return null;return <AccountSection title={`Pedido #${order.id}`} subtitle="15 Ago 2026"><Card className="p-5"><div className="flex justify-between"><span>Status</span><StatusBadge status={order.status} label={statusLabels[order.status]}/></div><div className="mt-4 flex justify-between border-t border-stone-100 pt-4"><span>Total</span><PriceDisplay value={order.total}/></div><Link to="/"><Button className="mt-6 w-full"><RotateCcw size={17}/>Pedir novamente</Button></Link></Card></AccountSection> }
export function AddressesPage(){return <AccountSection title="Endereços" subtitle="Locais guardados para pedir mais rápido."><div className="grid gap-4 sm:grid-cols-2"><Card className="p-5"><div className="flex justify-between"><span className="grid size-10 place-items-center rounded-xl bg-brand-50 text-brand-600"><Home/></span><Button variant="ghost" size="sm"><Pencil size={16}/></Button></div><h3 className="mt-4 font-bold">Casa <span className="ml-2 text-xs text-emerald-600">Padrão</span></h3><p className="mt-2 text-sm text-stone-500">Polana Cimento · Portão azul</p></Card><button className="grid min-h-40 place-items-center rounded-2xl border border-dashed border-stone-300 bg-white text-sm font-bold text-brand-600"><span><Plus className="mx-auto mb-2"/>Novo endereço</span></button></div></AccountSection>}
export function SecurityPage(){return <AccountSection title="Segurança" subtitle="Proteja o acesso à sua conta."><Card className="p-5"><div className="flex items-center gap-4"><span className="grid size-11 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><ShieldCheck/></span><div className="flex-1"><p className="font-bold">Senha da conta</p><p className="text-sm text-stone-500">Última alteração há 3 meses</p></div><Button variant="secondary">Alterar</Button></div></Card></AccountSection>}
function AccountSection({title,subtitle,children}){ const location=useLocation();return <div className="page-shell py-8"><Link to="/conta" className="text-sm font-bold text-stone-500">← Minha conta</Link><div className="mt-5 grid gap-6 lg:grid-cols-[220px_1fr]"><aside className="hidden lg:block"><nav className="space-y-1">{menu.map(([to,label,Icon])=><Link key={to} to={to} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold ${location.pathname.startsWith(to)?'bg-white text-brand-600 shadow-sm':'text-stone-500'}`}><Icon size={18}/>{label}</Link>)}</nav></aside><section><h1 className="font-display text-4xl font-bold">{title}</h1><p className="mb-6 mt-2 text-sm text-stone-500">{subtitle}</p>{children}</section></div></div>}
