import { forwardRef } from 'react'
import { Link } from 'react-router-dom'
import { AnimatePresence, motion } from 'framer-motion'
import { AlertCircle, Check, ChevronRight, ImageOff, LoaderCircle, Minus, Plus, Search, ShoppingBag, X } from 'lucide-react'
import { classNames, formatPrice } from '../../utils/format'

const variants={ primary:'bg-brand-500 text-white hover:bg-brand-600 shadow-sm', secondary:'bg-white text-ink border border-stone-200 hover:border-stone-300', ghost:'bg-transparent text-stone-700 hover:bg-stone-100', danger:'bg-red-600 text-white hover:bg-red-700', dark:'bg-ink text-white hover:bg-stone-800' }
export function Button({children,variant='primary',size='md',className='',loading=false,...props}) {
  return <button className={classNames('inline-flex items-center justify-center gap-2 rounded-xl font-bold transition disabled:cursor-not-allowed disabled:opacity-50', variants[variant], size==='sm'?'min-h-9 px-3 text-sm':size==='lg'?'min-h-13 px-6 text-base':'min-h-11 px-4 text-sm',className)} disabled={loading||props.disabled} {...props}>{loading&&<LoaderCircle size={17} className="animate-spin"/>}{children}</button>
}
export function IconButton({label,children,className='',...props}) { return <button aria-label={label} className={classNames('grid size-11 place-items-center rounded-full border border-stone-200 bg-white transition hover:bg-stone-50',className)} {...props}>{children}</button> }
export const Input=forwardRef(function Input({label,error,icon:Icon,className='',...props},ref){ return <label className={classNames('block',className)}>{label&&<span className="mb-2 block text-sm font-bold text-stone-700">{label}</span>}<span className="relative block">{Icon&&<Icon className="absolute left-3.5 top-1/2 -translate-y-1/2 text-stone-400" size={18}/>}<input ref={ref} className={classNames('h-12 w-full rounded-xl border bg-white px-4 text-sm outline-none transition placeholder:text-stone-400',Icon&&'pl-11',error?'border-red-400':'border-stone-200 focus:border-brand-500')} {...props}/></span>{error&&<span className="mt-1.5 block text-xs font-medium text-red-600">{error}</span>}</label> })
export const Select=forwardRef(function Select({label,error,children,className='',...props},ref){ return <label className={classNames('block',className)}>{label&&<span className="mb-2 block text-sm font-bold text-stone-700">{label}</span>}<select ref={ref} className="h-12 w-full rounded-xl border border-stone-200 bg-white px-4 text-sm outline-none focus:border-brand-500" {...props}>{children}</select>{error&&<span className="mt-1.5 block text-xs font-medium text-red-600">{error}</span>}</label> })
export const Textarea=forwardRef(function Textarea({label,error,className='',...props},ref){ return <label className={classNames('block',className)}>{label&&<span className="mb-2 block text-sm font-bold text-stone-700">{label}</span>}<textarea ref={ref} className="min-h-24 w-full resize-none rounded-xl border border-stone-200 bg-white px-4 py-3 text-sm outline-none focus:border-brand-500" {...props}/>{error&&<span className="mt-1.5 block text-xs font-medium text-red-600">{error}</span>}</label> })
export function SearchInput({value,onChange,placeholder='Pesquisar no cardápio...'}) { return <div className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-stone-400" size={20}/><input value={value} onChange={onChange} placeholder={placeholder} aria-label="Pesquisar" className="h-13 w-full rounded-2xl border border-stone-200 bg-white pl-12 pr-4 text-sm shadow-sm outline-none focus:border-brand-500"/></div> }
export function Card({children,className=''}) { return <div className={classNames('min-w-0 rounded-2xl border border-stone-200/80 bg-white shadow-sm',className)}>{children}</div> }
export function Badge({children,tone='neutral',className=''}) { const tones={neutral:'bg-stone-100 text-stone-700',green:'bg-emerald-50 text-emerald-700',amber:'bg-amber-50 text-amber-700',blue:'bg-blue-50 text-blue-700',orange:'bg-orange-50 text-orange-700',violet:'bg-violet-50 text-violet-700',red:'bg-red-50 text-red-700'}; return <span className={classNames('inline-flex items-center rounded-full px-2.5 py-1 text-xs font-bold',tones[tone]||tones.neutral,className)}>{children}</span> }
export function StatusBadge({status,label}) { const tones={RECEIVED:'amber',CONFIRMED:'blue',PREPARING:'orange',READY_FOR_DELIVERY:'green',OUT_FOR_DELIVERY:'violet',DELIVERED:'green',CANCELLED:'red',READY:'green',COMPLETED:'green'}; return <Badge tone={tones[status]}>{label}</Badge> }
export function QuantitySelector({value,onChange,min=1}) { return <div className="inline-flex items-center rounded-xl border border-stone-200 bg-white p-1"><button aria-label="Diminuir" className="grid size-8 place-items-center rounded-lg hover:bg-stone-100" onClick={()=>onChange(Math.max(min,value-1))}><Minus size={16}/></button><span className="w-8 text-center text-sm font-bold">{value}</span><button aria-label="Aumentar" className="grid size-8 place-items-center rounded-lg hover:bg-stone-100" onClick={()=>onChange(value+1)}><Plus size={16}/></button></div> }
export function PriceDisplay({value,className=''}) { return <span className={classNames('font-extrabold tabular-nums',className)}>{formatPrice(value)}</span> }
export function Skeleton({className=''}) { return <div className={classNames('animate-pulse rounded-xl bg-stone-200',className)}/> }
export function EmptyState({title='Ainda não há nada aqui',description,action}) { return <div className="grid min-h-64 place-items-center rounded-2xl border border-dashed border-stone-300 bg-white p-8 text-center"><div><div className="mx-auto mb-4 grid size-14 place-items-center rounded-full bg-stone-100"><ShoppingBag className="text-stone-400"/></div><h3 className="font-display text-xl font-bold">{title}</h3>{description&&<p className="mt-2 text-sm text-stone-500">{description}</p>}{action&&<div className="mt-5">{action}</div>}</div></div> }
export function ErrorState({message='Não foi possível carregar. Tente novamente.'}) { return <div className="flex items-center gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><AlertCircle size={20}/>{message}</div> }
export function Drawer({open,onClose,title,children,footer}) { return <AnimatePresence>{open&&<><motion.button aria-label="Fechar" className="fixed inset-0 z-40 bg-black/35" onClick={onClose} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/><motion.aside className="fixed inset-y-0 right-0 z-50 flex w-full max-w-md flex-col bg-cream shadow-2xl" initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{duration:.22}}><div className="flex items-center justify-between border-b border-stone-200 px-5 py-4"><h2 className="font-display text-xl font-bold">{title}</h2><IconButton label="Fechar" onClick={onClose}><X size={20}/></IconButton></div><div className="flex-1 overflow-auto p-5">{children}</div>{footer&&<div className="border-t border-stone-200 bg-white p-5">{footer}</div>}</motion.aside></>}</AnimatePresence> }
export function Modal({open,onClose,title,children}) { return <AnimatePresence>{open&&<div className="fixed inset-0 z-50 grid place-items-center p-4"><motion.button aria-label="Fechar" className="absolute inset-0 bg-black/45" onClick={onClose} initial={{opacity:0}} animate={{opacity:1}}/><motion.div className="relative z-10 max-h-[90vh] w-full max-w-lg overflow-auto rounded-2xl bg-white p-6 shadow-2xl" initial={{opacity:0,y:16,scale:.98}} animate={{opacity:1,y:0,scale:1}}><div className="mb-5 flex items-center justify-between"><h2 className="font-display text-2xl font-bold">{title}</h2><IconButton label="Fechar" onClick={onClose}><X size={20}/></IconButton></div>{children}</motion.div></div>}</AnimatePresence> }
export function Stepper({steps,current}) { return <div className="flex items-center justify-between">{steps.map((step,index)=><div key={step} className="flex flex-1 items-center last:flex-none"><div className="flex flex-col items-center gap-1"><span className={classNames('grid size-8 place-items-center rounded-full text-xs font-bold',index<=current?'bg-brand-500 text-white':'bg-stone-200 text-stone-500')}>{index<current?<Check size={15}/>:index+1}</span><span className="hidden text-[11px] font-semibold text-stone-500 sm:block">{step}</span></div>{index<steps.length-1&&<span className={classNames('mx-2 h-px flex-1',index<current?'bg-brand-500':'bg-stone-200')}/>}</div>)}</div> }
export function ProductCard({product,onAdd}) { return <motion.article layout className="group overflow-hidden rounded-2xl border border-stone-200/70 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-soft"><Link to={`/produto/${product.slug}`} className="relative block aspect-[4/3] overflow-hidden food-image"><img src={product.image} alt={product.name} loading="lazy" className="size-full object-cover transition duration-500 group-hover:scale-105" onError={(event)=>{event.currentTarget.style.display='none'}}/>{product.featured&&<Badge className="absolute left-3 top-3 bg-white/90">Destaque</Badge>}{!product.available&&<span className="absolute inset-0 grid place-items-center bg-black/45 text-sm font-bold text-white"><ImageOff size={18} className="mr-2"/> Indisponível</span>}</Link><div className="p-4"><Link to={`/produto/${product.slug}`}><h3 className="font-display text-lg font-bold leading-tight group-hover:text-brand-600">{product.name}</h3><p className="mt-1.5 line-clamp-2 min-h-10 text-sm leading-5 text-stone-500">{product.description}</p></Link><div className="mt-4 flex items-center justify-between"><PriceDisplay value={product.price}/><Button size="sm" disabled={!product.available} onClick={()=>onAdd(product)}><Plus size={16}/> Adicionar</Button></div></div></motion.article> }
export function SectionHeading({eyebrow,title,description,action}) { return <div className="mb-6 flex items-end justify-between gap-4"><div>{eyebrow&&<p className="mb-2 text-xs font-extrabold uppercase tracking-[.18em] text-brand-600">{eyebrow}</p>}<h2 className="font-display text-3xl font-bold tracking-tight md:text-4xl">{title}</h2>{description&&<p className="mt-2 max-w-2xl text-sm text-stone-500 md:text-base">{description}</p>}</div>{action}</div> }
export function OfflineBanner(){ return <div className="fixed inset-x-0 bottom-0 z-[70] bg-ink px-4 py-2 text-center text-xs font-semibold text-white">Sem ligação à internet. Algumas informações podem estar desactualizadas.</div> }
export function Table({columns,rows,onRowClick}) { return <div className="max-w-full overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr className="border-b border-stone-200 text-xs uppercase tracking-wider text-stone-400">{columns.map((column)=><th key={column.key} className="px-4 py-3 font-bold">{column.label}</th>)}</tr></thead><tbody>{rows.map((row)=><tr key={row.id} onClick={()=>onRowClick?.(row)} className={classNames('border-b border-stone-100 last:border-0',onRowClick&&'cursor-pointer hover:bg-stone-50')}>{columns.map((column)=><td key={column.key} className="px-4 py-4">{column.render?column.render(row):row[column.key]}</td>)}</tr>)}</tbody></table></div> }
export function Breadcrumb({items}) { return <nav className="mb-5 flex items-center gap-1 text-xs font-semibold text-stone-500">{items.map((item,index)=><span key={item.label} className="flex items-center">{item.href?<Link className="hover:text-brand-600" to={item.href}>{item.label}</Link>:item.label}{index<items.length-1&&<ChevronRight size={14} className="mx-1"/>}</span>)}</nav> }
